version: 2.1

jobs:
  "docker-build":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/0/docker-build

  "base_18_04":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/1/base-18.04

  "base_20_04":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/1/base-20.04

  "clang_4":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/clang-4

  "clang_5":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/clang-5

  "clang_6":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/clang-6

  "clang_7":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/clang-7

  "clang_8":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/clang-8

  "clang_9":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/clang-9

  "clang_10":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/public dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/clang-10

  "gcc_5":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/gcc-5

  "gcc_6":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/gcc-6

  "gcc_7":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/gcc-7

  "gcc_8":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/gcc-8

  "gcc_9":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/gcc-9

  "gcc_10":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/publish dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/2/gcc-10

  "clang_10_libstdcpp":
    docker:
      - image: johnmcfarlane/cnl_ci:docker-build
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build/public dockerfile
          command: |
            echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin &&
            ./build.py dockerfiles/3/clang-10-libstdcpp

workflows:
  version: 2
  build-images:
    jobs:
      - docker-build

      - base_18_04:
          requires:
            - docker-build

      - base_20_04:
          requires:
            - docker-build

      - clang_4:
          requires:
            - base_18_04
      - clang_5:
          requires:
            - base_18_04
      - clang_6:
          requires:
            - base_20_04
      - clang_7:
          requires:
            - base_20_04
      - clang_8:
          requires:
            - base_20_04
      - clang_9:
          requires:
            - base_20_04
      - clang_10:
          requires:
            - base_20_04

      - gcc_5:
          requires:
            - base_18_04
      - gcc_6:
          requires:
            - base_18_04
      - gcc_7:
          requires:
            - base_20_04
      - gcc_8:
          requires:
            - base_20_04
      - gcc_9:
          requires:
            - base_20_04
      - gcc_10:
          requires:
            - base_20_04

      - clang_10_libstdcpp:
          requires:
            - clang_10
