version: 2

jobs:
  "base-19.10":
    docker:
      - image: ubuntu:19.10
    steps:
      - checkout
      - run:
          name: Build/public dockerfile
          command: build.py dockerfiles/0/base-19.10

workflows:
  version: 2
  test:
    jobs:
#      - base-18.04
      - base-19.10
#      - clang-4.0
#      - clang-5.0
#      - clang-6.0
#      - clang-7.0
#      - clang-8.0
#      - clang-9.0
#      - gcc-5
#      - gcc-6
#      - gcc-7
#      - gcc-8
#      - gcc-9
#      - clang-9.0-msan
